apiVersion: v1
kind: Service
metadata:
  name: web-academy-nginx-service
spec:
  type: NodePort
  selector:
    app: web-academy-nginx
  ports:
  - protocol: TCP
    port: 81
    targetPort: 80
    nodePort: 30001
